### ISSUE TITLE
Crashes immediately on touching "Schedule" in the menu

### ISSUE THREAD

**Issue by Mikaela** [SecUSo/privacy-friendly-wifi-manager#14]
Nokia 1, I was attempting to see if the schedule menu allowed me to disable WLAN for saving battery while I slept as I think WiFi Manager keeps activating it regardless of my manual disabling. I hope the `adb logcat|grep secuso` is of any use:

```adb
01-27 00:23:14.255   292   861 I BufferQueueProducer: [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0](this:0xa1678000,id:2424,api:1,p:3360,c:292) queueBuffer: fps=4.86 dur=6169.95 max=5441.30 min=9.24
01-27 00:23:14.329  3360  3360 E AndroidRuntime: Process: org.secuso.privacyfriendlywifimanager, PID: 3360
01-27 00:23:14.329  3360  3360 E AndroidRuntime: android.view.InflateException: Binary XML file line #0: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
01-27 00:23:14.329  3360  3360 E AndroidRuntime: Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
01-27 00:23:14.329  3360  3360 E AndroidRuntime: 	at org.secuso.privacyfriendlywifimanager.view.fragment.ScheduleFragment.onCreateView(ScheduleFragment.java:88)
01-27 00:23:14.329  3360  3360 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
01-27 00:23:14.329  3360  3360 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior" on path: DexPathList[[zip file "/data/app/org.secuso.privacyfriendlywifimanager-Ojp8xWHaOAk1_NzySXskzg==/base.apk"],nativeLibraryDirectories=[/data/app/org.secuso.privacyfriendlywifimanager-Ojp8xWHaOAk1_NzySXskzg==/lib/arm, /system/lib, /vendor/lib]]
01-27 00:23:14.337   735  1961 W ActivityManager:   Force finishing activity org.secuso.privacyfriendlywifimanager/.view.MainActivity
01-27 00:23:14.356   735   751 I ActivityManager: Showing crash dialog for package org.secuso.privacyfriendlywifimanager u0
01-27 00:23:14.450   735   757 I WindowManager: Focus moving from Window{951759c u0 org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity} to Window{1ce39 u0 Application Error: org.secuso.privacyfriendlywifimanager}
01-27 00:23:14.478   292   292 I BufferQueueConsumer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:0,p:-1,c:292) setConsumerName: Application Error: org.secuso.privacyfriendlywifimanager#0
01-27 00:23:14.478   292   292 I BufferQueueConsumer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:0,p:-1,c:292) setDefaultBufferSize: width=445 height=245
01-27 00:23:14.505   292   329 I BufferQueueProducer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:2,p:735,c:292) connect(P): api=2 producer=(735:system_server) producerControlledByApp=false
01-27 00:23:14.542   735   757 I WindowManager: Losing delayed focus: Window{951759c u0 org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity}
01-27 00:23:14.845   735   750 W ActivityManager: Activity pause timeout for ActivityRecord{5644a96 u0 org.secuso.privacyfriendlywifimanager/.view.MainActivity t1672 f}
01-27 00:23:14.901   292   292 I SurfaceFlinger: screenshot (org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0)
01-27 00:23:15.019  3421  3447 I PandorasBoxService: [Thread-2] Log.fih("BBSAPP::UPD", "8::data_app_crash;org.secuso.privacyfriendlywifimanager;org.secuso.privacyfriendlywifimanager|1|1.0;Binary XML file line #0: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior")
01-27 00:23:15.126   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:1.00 cannot be handled by hwcomposer
01-27 00:23:15.143   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.99 cannot be handled by hwcomposer
01-27 00:23:15.160   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.96 cannot be handled by hwcomposer
01-27 00:23:15.177   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.90 cannot be handled by hwcomposer
01-27 00:23:15.193   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.83 cannot be handled by hwcomposer
01-27 00:23:15.210   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.73 cannot be handled by hwcomposer
01-27 00:23:15.230   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.62 cannot be handled by hwcomposer
01-27 00:23:15.246   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.49 cannot be handled by hwcomposer
01-27 00:23:15.261   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.34 cannot be handled by hwcomposer
01-27 00:23:15.278   292   292 W Layer   : [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0] opaque layer with plane alpha:0.16 cannot be handled by hwcomposer
01-27 00:23:15.794  3448  3464 I StabilityMonitor: [ParserUtility] key word : org.secuso.privacyfriendlywifimanager
01-27 00:23:15.798  3448  3464 I StabilityMonitor: [APRReport] exceptionItem  tag:data_app_crash packageName:org.secuso.privacyfriendlywifimanager versionCode:1 versionName:1.0
01-27 00:23:15.801   292   330 I BufferQueueProducer: [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0](this:0xa1678000,id:2424,api:1,p:3360,c:292) disconnect(P): api 1
01-27 00:23:15.801   292   330 I BufferQueueConsumer: [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0](this:0xa1678000,id:2424,api:1,p:-1,c:292) getReleasedBuffers: returning mask 0xffffffffffffffff
01-27 00:23:15.803   735  1344 I WindowManager: WIN DEATH: Window{951759c u0 org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity}
01-27 00:23:15.805   735  2608 I ActivityManager: Process org.secuso.privacyfriendlywifimanager (pid 3360) has died: cch  CEM 
01-27 00:23:15.818   292   292 I BufferQueueConsumer: [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0](this:0xa1678000,id:2424,api:1,p:-1,c:-1) disconnect(C)
01-27 00:23:15.819   292   292 I BufferQueue: [org.secuso.privacyfriendlywifimanager/org.secuso.privacyfriendlywifimanager.view.MainActivity#0](this:0xa1678000,id:2424,api:1,p:-1,c:-1) ~BufferQueueCore
01-27 00:23:15.838  3448  3464 E STBIntentService: send error message:data_app_crash;1548541394345(pkgName:org.secuso.privacyfriendlywifimanager;version:1.0;versionCode:1) to BBS for ANR/FC/TOMB_STONE...
01-27 00:23:15.856  3448  3464 E STBMonitorQueue: restore data:/data/system/dropbox/data_app_crash@1548541253657.txt;1;1.0;org.secuso.privacyfriendlywifimanager into shortQue queue...
01-27 00:23:15.856  3448  3464 E STBMonitorQueue: restore data:/data/system/dropbox/data_app_crash@1548541259472.txt;1;1.0;org.secuso.privacyfriendlywifimanager into shortQue queue...
01-27 00:23:15.856  3448  3464 E STBMonitorQueue: restore data:/data/system/dropbox/data_app_crash@1548541308514.txt;1;1.0;org.secuso.privacyfriendlywifimanager into shortQue queue...
01-27 00:23:15.857  3448  3464 E STBMonitorQueue: restore data:/data/system/dropbox/data_app_crash@1548541366591.txt;1;1.0;org.secuso.privacyfriendlywifimanager into shortQue queue...
01-27 00:23:15.862   735  1961 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{119f7b7 0:org.secuso.privacyfriendlywifimanager/u0a176}
01-27 00:23:15.867   735   757 I WindowManager: Focus moving from Window{1ce39 u0 Application Error: org.secuso.privacyfriendlywifimanager EXITING} to Window{d0f7fb0 u0 fr.neamar.kiss/fr.neamar.kiss.MainActivity}
01-27 00:23:16.005   292   861 I BufferQueueProducer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:2,p:735,c:292) disconnect(P): api 2
01-27 00:23:16.005   292   861 I BufferQueueConsumer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:2,p:-1,c:292) getReleasedBuffers: returning mask 0xffffffffffffffff
01-27 00:23:16.015   292   292 I BufferQueueConsumer: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:2,p:-1,c:-1) disconnect(C)
01-27 00:23:16.016   292   292 I BufferQueue: [Application Error: org.secuso.privacyfriendlywifimanager#0](this:0xa107d000,id:2425,api:2,p:-1,c:-1) ~BufferQueueCore
```

**Comment by petermayer** [comment]
Thanks for the report, we will investigate it.

**Comment by Akito13** [comment]
I can confirm this behaviour.

**Comment by cweiske** [comment]
I get a different crash log:
```
FATAL EXCEPTION: main
Process: org.secuso.privacyfriendlywifimanager, PID: 13853
android.view.InflateException: Binary XML file line #0: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:601)
	at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2540)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1601)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at org.secuso.privacyfriendlywifimanager.view.fragment.ScheduleFragment.onCreateView(ScheduleFragment.java:88)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.ClassNotFoundException: org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:593)
	... 21 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior" on path: DexPathList[[zip file "/data/app/org.secuso.privacyfriendlywifimanager-1/base.apk"],nativeLibraryDirectories=[/data/app/org.secuso.privacyfriendlywifimanager-1/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 24 more
```

**Comment by TjrGithub** [comment]
I can confirm, too.

Running on a freshly installed LineageOS 15.1 on Xiaomi Redmi Note 4 with addon_su. Xposed and XprivacyLua are installed but do not restrict the app. https://download.lineage.microg.org/mido/lineage-15.1-20190327-microG-mido.zip

FATAL EXCEPTION: main
Process: org.secuso.privacyfriendlywifimanager, PID: 30978
android.view.InflateException: Binary XML file line #0: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:601)
	at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2540)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1601)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.secuso.privacyfriendlywifimanager.view.fragment.ScheduleFragment.onCreateView(ScheduleFragment.java:88)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: java.lang.ClassNotFoundException: org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:593)
	... 25 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior" on path: DexPathList[[zip file "/data/app/org.secuso.privacyfriendlywifimanager-xv_xyiQ8BlCj5IxXP-k1cg==/base.apk"],nativeLibraryDirectories=[/data/app/org.secuso.privacyfriendlywifimanager-xv_xyiQ8BlCj5IxXP-k1cg==/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 28 more

**Comment by petermayer** [comment]
Just a quick update. We are currently not able to reproduce this with the devices at our disposal, but we continue to investigate it.

**Comment by cweiske** [comment]
I am using it on LineageOS 14.1 (Android 7.1.2), a Wileyfox Swift.
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Comment by m-rey** [comment]
Hello, I'm also having this error using a Xiaomi redmi note 5 with MIUI Global 10.2 (Android 8.1.0):
```
android.view.InflateException: Binary XML file line #0: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:601)
	at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2540)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1601)
	at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:106)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at org.secuso.privacyfriendlywifimanager.view.fragment.ScheduleFragment.onCreateView(ScheduleFragment.java:88)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:593)
	... 21 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.secuso.privacyfriendlywifi.view.behavior.ScrollAwareFABBehavior" on path: DexPathList[[zip file "/data/app/org.secuso.privacyfriendlywifimanager-HOskgKPmVULSdeVn3tB7Kw==/base.apk"],nativeLibraryDirectories=[/data/app/org.secuso.privacyfriendlywifimanager-HOskgKPmVULSdeVn3tB7Kw==/lib/arm64, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 24 more
```

**Comment by cweiske** [comment]
The solution is there: https://stackoverflow.com/a/46029836

**Comment by heapifyman** [comment]
Same here. LineageOS 15.1 for microG on Fairphone 2

**Comment by devurandom** [comment]
Perfectly reproducible on two devices:
* Fairphone FP2 with Fairphone Open 19.02.1 (Android 7.1.2)
* Samsung Galaxy S4 mini with LineageOS 14.1-20180624-NIGHTLY-serranoltexx (Android 7.1.2)

**Comment by un-logic** [comment]
Also reproduces on Google's Nexus 4 with stock Android 5.1.1. Any plans to fix it?

**Comment by Kamuno** [comment]
Thanks for your reports and sorry that it took so long. The update will go live soon.
